### ISSUE TITLE
Could not verify the provided CSRF token

### ISSUE THREAD

**Issue by annahenke** [SAP-samples/cloud-alm-api-examples#10]
Hi,

I have installed and started the Kanban example as described, but keep getting an error "Could not verify the provided CSRF token no token was found to compare." code: 'EAUTH'.
I can see the board, but after this error the connection to the server is aborted.

The complete output is: 

```
kanban4calmserver listening on port 3000
to access the application use http://localhost:3000
Get Projects called
C:\Users\myuser\Tools\cloud-alm-api-examples-main\applications\kanban4calm\server\node_modules\client-oauth2\src\client-oauth2.js:122
    var err = new Error(message)
              ^

Error: Could not verify the provided CSRF token because no token was found to compare.
    at getAuthError (C:\Users\myuser\Tools\cloud-alm-api-examples-main\applications\kanban4calm\server\node_modules\client-oauth2\src\client-oauth2.js:122:15)
    at C:\Users\myuser\Tools\cloud-alm-api-examples-main\applications\kanban4calm\server\node_modules\client-oauth2\src\client-oauth2.js:276:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  body: {
    error: 'Could not verify the provided CSRF token because no token was found to compare.'
  },
  code: 'EAUTH'
}

Node.js v18.12.1
```

I am still not 100% sure that the parameters I provided in the config.json are correct, because the information about the parameters we get from our ClouALM instance does not use the same naming for the parameters. Maybe clarifying this could also resolve the issue here.

Thank you,
Anna

**Comment by Mkloeffer** [comment]
Hi Anna,

I assume there is an error in the config.json, or with the service configuration of the API. Would you mind showing an obfuscated config.json, just to be sure that it is no typos in there? You have to make sure to not have a trailing / in the API URL and everything quoted in double quotes...

Thanks, Michael
